[project]
name = "deep-rl-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gymnasium[box2d]>=1.2.0",
    "stable-baselines3[extra]>=2.7.0",
]
